# Orbital TNT 钓鱼竿配置文件

orbital-tnt:
  # 是否启用此功能
  enabled: true
  
  # 钓鱼竿显示名称（必须完全匹配）
  fishing-rod-name: "Orbital TNT"

  #抛竿后等待时长（毫秒）
  wait-time: 5000

  #生成tnt圆环数量
  circle-count: 5

  #每个tnt圆环间隔的距离
  circle-interval: 2

  #tnt圆环生成高度
  circle-height: 5

  #每个圆环等待时长（毫秒）
  per-circle-wait-time: 10

  # 抛竿后释放的距离(格)
  release-distance: 10